server_name = "matrix.si46.world"

address = "0.0.0.0"
port = 6167

max_request_size = 20000000

allow_federation = true
trusted_servers = ["matrix.org"]

allow_check_for_updates = true
database_path = "/var/lib/tuwunel"

allow_registration = true
registration_requires_token = true

[[registration_tokens]]
token = "team-internal"
uses_allowed = 20
