[global]

# 基本服务器配置
server_name = "matrix.si46.world"

# 监听配置
address = "0.0.0.0"
port = 6167

# 请求限制
max_request_size = 20000000

# 联邦
allow_federation = true
trusted_servers = ["matrix.org"]

# 其他
allow_check_for_updates = true
database_path = "/var/lib/tuwunel"

# 注册配置
allow_registration = true  # 启用注册
registration_requires_token = true  # 强制需要 token（否则公开注册）
registration_token = "7a4234d2e408f5b43fde6c144ba2c7ea17ccc0b110957fff65a8ffc9619d68b6"
